version: '3'
services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: dev
    stdin_open: true
    tty: true
    ports:
      - "9999:9999"
    depends_on:
      - postgres
    volumes:
      - ./server:/go/src/shimo0108-app/server
    container_name: 'server'

  postgres:
    stdin_open: true
    tty: true
    restart: always
    container_name: postgres
    hostname: db
    build:
      context: .
      dockerfile: ./server/postgres/Dockerfile
    environment:
      - POSTGRES_USER=shimo0108
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shimo_app_db
    volumes:
      - postgres-data-volume:/var/lib/postgresql
      - ./server/postgres/init/:/docker-entrypoint-initdb.d

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    command: npm run local-serve
    ports:
      - '8080:8080'
    volumes:
      - ./client:/client
    container_name: 'client'
volumes:
  postgres-data-volume:
    name: postgres-data
    driver: local
